"""add example_sentence column to VocabEntry

Revision ID: 7906787c94bb
Revises: fe861cb2a964
Create Date: 2026-06-28 21:46:02.186547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7906787c94bb'
down_revision: Union[str, Sequence[str], None] = 'fe861cb2a964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_entries', sa.Column('example_sentence', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab_entries', 'example_sentence')
    # ### end Alembic commands ###
