"""add user_id to themes

Revision ID: 6e68744040bd
Revises: 9a31d73b8e06
Create Date: 2026-08-23 18:15:04.566854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e68744040bd'
down_revision: Union[str, Sequence[str], None] = '9a31d73b8e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'themes', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_column('themes', 'user_id')
    # ### end Alembic commands ###
