"""drop_lang_pair_column_in_entries

Revision ID: a8b804e6e7a7
Revises: 7906787c94bb
Create Date: 2026-07-08 15:02:31.303263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b804e6e7a7'
down_revision: Union[str, Sequence[str], None] = '7906787c94bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab_entries', 'language_pair')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_entries', sa.Column('language_pair', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
